---
# SPDX-FileCopyrightText: 2025 Margo
#
# SPDX-License-Identifier: MIT
#
# SPDX-FileContributor: Michael Adler <michael.adler@siemens.com>
name: ci

on:
  push:
    paths:
      - 'conf/**'
      - 'recipes-*/**'
      - 'kas/**/*.yml'
      - '*.yml'
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-margo-device:
    name: Margo Device ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Build image
        run: ./kas-container build kas-margo.yml:kas/margo-device.yml:kas/board/qemu-${{ matrix.arch }}.yml
      - run: find build/tmp/deploy/images
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: qemu-${{ matrix.arch }}
          path: build/tmp/deploy/images/qemu-${{ matrix.arch }}
